/* ═══════════════════════════════════════════════════════
   SVS Beauty Space — Shop Product Data
   Generated from price lists: Raywell, Extremo, Envie, Invidia
   ═══════════════════════════════════════════════════════ */

var SHOP_BRANDS = [
  { id: 'raywell', name: 'Raywell' },
  { id: 'extremo', name: 'Extremo' },
  { id: 'envie', name: 'Envie' },
  { id: 'invidia', name: 'Invidia' },
];

var SHOP_CATEGORIES = [
  { id: 'coloring', name: 'Фарбування та освітлення', icon: '◆' },
  { id: 'care', name: 'Догляд за волоссям', icon: '◇' },
  { id: 'repair', name: 'Відновлення', icon: '◈' },
  { id: 'styling', name: 'Стайлінг', icon: '⬥' },
  { id: 'special', name: 'Спеціальний догляд', icon: '✧' },
];

var SHOP_PRODUCTS = [

  // ══════════════════════════════════════════════════════
  //  RAYWELL — Фарбування та освітлення
  // ══════════════════════════════════════════════════════
  {
    id: 'rw-eterna-100',
    category: 'coloring',
    brand: 'raywell',
    name: 'Фарба Eterna',
    price: 676,
    volume: '100 мл',
    desc: 'Стійка крем-фарба для волосся',
    badge: null,
    popular: true,
  },
  {
    id: 'rw-eterna-set-4',
    category: 'coloring',
    brand: 'raywell',
    name: 'Набір фарб Eterna (4 тюбики)',
    price: 3952,
    volume: '4x100 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-oxid-tools',
    category: 'coloring',
    brand: 'raywell',
    name: 'Окисник Tools',
    price: 697,
    volume: '1 л',
    desc: 'Окисник 10/20/30/40 vol',
    badge: null,
    popular: true,
  },
  {
    id: 'rw-oxid-blond',
    category: 'coloring',
    brand: 'raywell',
    name: 'Окисник Tools Blond',
    price: 1113,
    volume: '1 л',
    desc: 'Окисник для блонду 10/20/30 vol',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-color-drops',
    category: 'coloring',
    brand: 'raywell',
    name: 'Краплі інтенсивного кольору',
    price: 2080,
    volume: '35 мл',
    desc: 'Пігмент для посилення кольору',
    badge: 'hit',
    popular: true,
  },
  {
    id: 'rw-bleach-oil',
    category: 'coloring',
    brand: 'raywell',
    name: 'Освітлююча олія',
    price: 1882,
    volume: '500 мл',
    desc: 'Олія для м\'якого освітлення',
    badge: null,
    popular: true,
  },
  {
    id: 'rw-deko-violet',
    category: 'coloring',
    brand: 'raywell',
    name: 'Висвітлююча пудра фіолетова Deko Violet',
    price: 2184,
    volume: '500 г',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-powder-ammonia-1kg',
    category: 'coloring',
    brand: 'raywell',
    name: 'Висвітлююча пудра з аміаком',
    price: 3120,
    volume: '1 кг',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-powder-noammonia-1kg',
    category: 'coloring',
    brand: 'raywell',
    name: 'Висвітлююча пудра без аміаку',
    price: 3328,
    volume: '1 кг',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-bleach-plex',
    category: 'coloring',
    brand: 'raywell',
    name: 'Знебарвлюючий крем Bleach Plex',
    price: 4160,
    volume: '500 мл',
    desc: 'Крем для знебарвлення з плекс-захистом',
    badge: 'new',
    popular: true,
  },
  {
    id: 'rw-powder-9tones',
    category: 'coloring',
    brand: 'raywell',
    name: 'Висвітлююча пудра до 9 тонів',
    price: 2392,
    volume: '500 г',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-powder-7tones',
    category: 'coloring',
    brand: 'raywell',
    name: 'Висвітлююча пудра до 7 тонів',
    price: 2288,
    volume: '500 г',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-color-remover',
    category: 'coloring',
    brand: 'raywell',
    name: 'Рідина для змиття фарби',
    price: 718,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },

  // ══════════════════════════════════════════════════════
  //  RAYWELL — Догляд за волоссям
  // ══════════════════════════════════════════════════════
  {
    id: 'rw-conditioner-5l',
    category: 'care',
    brand: 'raywell',
    name: 'Кондиціонер/бальзам',
    price: 3432,
    volume: '5 л',
    desc: 'Професійний об\'єм',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-close-color-shampoo',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь Close Color',
    price: 1768,
    volume: '1000 мл',
    desc: 'Для збереження кольору після фарбування',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-close-color-cond',
    category: 'care',
    brand: 'raywell',
    name: 'Кондиціонер Close Color',
    price: 1638,
    volume: '1000 мл',
    desc: 'Для збереження кольору після фарбування',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-detox-spray',
    category: 'care',
    brand: 'raywell',
    name: 'Спрей-детокс від металів',
    price: 1040,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-deep-cleanse-shampoo',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь глибокої очистки',
    price: 1976,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-lamellar-shampoo-1l',
    category: 'care',
    brand: 'raywell',
    name: 'Ламелярний шампунь',
    price: 2184,
    volume: '1000 мл',
    desc: '',
    badge: 'hit',
    popular: true,
  },
  {
    id: 'rw-lamellar-shampoo-275',
    category: 'care',
    brand: 'raywell',
    name: 'Ламелярний шампунь',
    price: 749,
    volume: '275 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-lamellar-water-500',
    category: 'care',
    brand: 'raywell',
    name: 'Ламелярна вода',
    price: 1560,
    volume: '500 мл',
    desc: 'Глибоке зволоження та відновлення структури',
    badge: 'hit',
    popular: true,
  },
  {
    id: 'rw-lamellar-water-200',
    category: 'care',
    brand: 'raywell',
    name: 'Ламелярна вода',
    price: 1040,
    volume: '200 мл',
    desc: 'Глибоке зволоження та відновлення структури',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biocroma-shampoo-1l',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь для фарбованого волосся Bio Croma',
    price: 1789,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biocroma-shampoo-275',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь для фарбованого волосся Bio Croma',
    price: 905,
    volume: '275 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biocroma-mask-500',
    category: 'care',
    brand: 'raywell',
    name: 'Маска для фарбованого волосся Bio Croma',
    price: 1113,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biocroma-mask-245',
    category: 'care',
    brand: 'raywell',
    name: 'Маска для фарбованого волосся Bio Croma',
    price: 749,
    volume: '245 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biocroma-serum',
    category: 'care',
    brand: 'raywell',
    name: 'Серум для фарбованого волосся Bio Croma',
    price: 1612,
    volume: '95 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-bioblond-shampoo-1l',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь антижовтизна Bio Blond',
    price: 2184,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-bioblond-shampoo-275',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь антижовтизна Bio Blond',
    price: 1050,
    volume: '275 мл',
    desc: '',
    badge: null,
    popular: true,
  },
  {
    id: 'rw-bioblond-cond-1l',
    category: 'care',
    brand: 'raywell',
    name: 'Кондиціонер антижовтизна Bio Blond',
    price: 2288,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-bioblond-cond-275',
    category: 'care',
    brand: 'raywell',
    name: 'Кондиціонер антижовтизна Bio Blond',
    price: 1144,
    volume: '275 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-bioblond-spray',
    category: 'care',
    brand: 'raywell',
    name: 'Спрей антижовтизна Bio Blond',
    price: 1258,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biocurly-shampoo-1l',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь для кучерявого волосся Bio Curly',
    price: 2319,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biocurly-shampoo-275',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь для кучерявого волосся Bio Curly',
    price: 1144,
    volume: '275 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biocurly-cond-1l',
    category: 'care',
    brand: 'raywell',
    name: 'Кондиціонер для кучерявого волосся Bio Curly',
    price: 2319,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biocurly-cond-275',
    category: 'care',
    brand: 'raywell',
    name: 'Кондиціонер для кучерявого волосся Bio Curly',
    price: 1144,
    volume: '275 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biocurly-cream',
    category: 'care',
    brand: 'raywell',
    name: 'Крем для кучерявого волосся Bio Curly',
    price: 1331,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biovolume-shampoo-1l',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь для об\'єму Bio Volume',
    price: 2319,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biovolume-shampoo-275',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь для об\'єму Bio Volume',
    price: 1113,
    volume: '275 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biovolume-cond-1l',
    category: 'care',
    brand: 'raywell',
    name: 'Кондиціонер для об\'єму Bio Volume',
    price: 2319,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biovolume-cond-275',
    category: 'care',
    brand: 'raywell',
    name: 'Кондиціонер для об\'єму Bio Volume',
    price: 1196,
    volume: '275 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biovolume-spray',
    category: 'care',
    brand: 'raywell',
    name: 'Спрей для об\'єму Bio Volume',
    price: 1248,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-shampoo-moisture-250',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь зволожуючий',
    price: 749,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-shampoo-moisture-1l',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь зволожуючий',
    price: 1518,
    volume: '1 л',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-mask-moisture-250',
    category: 'care',
    brand: 'raywell',
    name: 'Маска зволожуюча',
    price: 707,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-mask-moisture-1l',
    category: 'care',
    brand: 'raywell',
    name: 'Маска зволожуюча',
    price: 1529,
    volume: '1 л',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-shampoo-daily-250',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь для щоденного користування',
    price: 749,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-shampoo-daily-1l',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь для щоденного користування',
    price: 1404,
    volume: '1 л',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-spray-2phase',
    category: 'care',
    brand: 'raywell',
    name: 'Спрей 2-х фазний об\'єм та реконструкція',
    price: 936,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-shampoo-smooth-1l',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь розгладжуючий',
    price: 1404,
    volume: '1 л',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-shampoo-smooth-250',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь розгладжуючий',
    price: 707,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-shampoo-smooth-100',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь розгладжуючий',
    price: 572,
    volume: '100 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-cond-smooth-1l',
    category: 'care',
    brand: 'raywell',
    name: 'Кондиціонер розгладжуючий',
    price: 1456,
    volume: '1 л',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-cond-smooth-250',
    category: 'care',
    brand: 'raywell',
    name: 'Кондиціонер розгладжуючий',
    price: 749,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-cond-smooth-100',
    category: 'care',
    brand: 'raywell',
    name: 'Кондиціонер розгладжуючий',
    price: 572,
    volume: '100 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-cream-10in1',
    category: 'care',
    brand: 'raywell',
    name: 'Крем 10 в 1',
    price: 1019,
    volume: '200 мл',
    desc: 'Мультифункціональний догляд',
    badge: 'hit',
    popular: true,
  },
  {
    id: 'rw-no-orange-shampoo',
    category: 'care',
    brand: 'raywell',
    name: 'Шампунь No Orange',
    price: 1383,
    volume: '1 л',
    desc: 'Нейтралізація помаранчевих відтінків',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-cream-triple',
    category: 'care',
    brand: 'raywell',
    name: 'Крем потрійної дії',
    price: 1123,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },

  // ══════════════════════════════════════════════════════
  //  RAYWELL — Відновлення
  // ══════════════════════════════════════════════════════
  {
    id: 'rw-dreamplex',
    category: 'repair',
    brand: 'raywell',
    name: 'Додаток Dreamplex',
    price: 832,
    volume: '300 мл',
    desc: 'Захист при хімічних процедурах',
    badge: null,
    popular: true,
  },
  {
    id: 'rw-biorepair-shampoo-1l',
    category: 'repair',
    brand: 'raywell',
    name: 'Відновлюючий шампунь Bio Repair',
    price: 1976,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biorepair-shampoo-275',
    category: 'repair',
    brand: 'raywell',
    name: 'Відновлюючий шампунь Bio Repair',
    price: 1009,
    volume: '275 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biorepair-mask-500',
    category: 'repair',
    brand: 'raywell',
    name: 'Відновлююча маска Bio Repair',
    price: 1331,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biorepair-mask-245',
    category: 'repair',
    brand: 'raywell',
    name: 'Відновлююча маска Bio Repair',
    price: 936,
    volume: '245 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biorepair-cream',
    category: 'repair',
    brand: 'raywell',
    name: 'Відновлюючий крем Bio Repair',
    price: 1092,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-biorepair-instant',
    category: 'repair',
    brand: 'raywell',
    name: 'Засіб для миттєвого відновлення Bio Repair',
    price: 1123,
    volume: '200 мл',
    desc: '',
    badge: 'hit',
    popular: true,
  },
  {
    id: 'rw-biorepair-intensive',
    category: 'repair',
    brand: 'raywell',
    name: 'Засіб для інтенсивного відновлення Bio Repair',
    price: 894,
    volume: '100 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-ampules-reconstruction',
    category: 'repair',
    brand: 'raywell',
    name: 'Ампули реконструкція ВІО',
    price: 1716,
    volume: '10 штук',
    desc: 'Інтенсивне відновлення в ампулах',
    badge: null,
    popular: true,
  },
  {
    id: 'rw-x16-primer',
    category: 'repair',
    brand: 'raywell',
    name: 'X16 Незмивний молекулярний праймер',
    price: 913,
    volume: '150 мл',
    desc: 'Молекулярне відновлення',
    badge: 'new',
    popular: true,
  },
  {
    id: 'rw-x17-mask',
    category: 'repair',
    brand: 'raywell',
    name: 'X17 Молекулярна маска',
    price: 1132,
    volume: '150 мл',
    desc: 'Молекулярне відновлення',
    badge: 'new',
    popular: true,
  },
  {
    id: 'rw-x19-spray',
    category: 'repair',
    brand: 'raywell',
    name: 'X19 Спрей з полімерами',
    price: 950,
    volume: '100 мл',
    desc: 'Молекулярне відновлення',
    badge: 'new',
    popular: true,
  },
  {
    id: 'rw-cactus-reconstructor',
    category: 'repair',
    brand: 'raywell',
    name: 'Реконструктор кактус',
    price: 1248,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-boto-24k-set',
    category: 'repair',
    brand: 'raywell',
    name: 'BOTO 24K набір міні (шампунь+філер+крем)',
    price: 2444,
    volume: '3х150',
    desc: 'Ботокс із 24-каратним золотом',
    badge: 'hit',
    popular: true,
  },
  {
    id: 'rw-thermo-molecular-spray',
    category: 'repair',
    brand: 'raywell',
    name: 'Термоактивний молекулярний репараційний спрей',
    price: 950,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },

  // ══════════════════════════════════════════════════════
  //  RAYWELL — Стайлінг
  // ══════════════════════════════════════════════════════
  {
    id: 'rw-thermo-spray',
    category: 'styling',
    brand: 'raywell',
    name: 'Термоактивний спрей',
    price: 1217,
    volume: '200 мл',
    desc: 'Термозахист та укладка',
    badge: null,
    popular: true,
  },
  {
    id: 'rw-styler-smooth-200',
    category: 'styling',
    brand: 'raywell',
    name: 'Стайлер для розгладження волосся',
    price: 915,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-styler-smooth-100',
    category: 'styling',
    brand: 'raywell',
    name: 'Стайлер для розгладження волосся',
    price: 572,
    volume: '100 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-fluid-curly',
    category: 'styling',
    brand: 'raywell',
    name: 'Флюїд для кучерявого волосся',
    price: 780,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },

  // ══════════════════════════════════════════════════════
  //  RAYWELL — Спеціальний догляд
  // ══════════════════════════════════════════════════════
  {
    id: 'rw-scalp-protect',
    category: 'special',
    brand: 'raywell',
    name: 'Захист для шкіри голови',
    price: 832,
    volume: '150 мл',
    desc: 'Захист при фарбуванні та освітленні',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-perm-lotion-1',
    category: 'special',
    brand: 'raywell',
    name: 'Лосьйон для завивки 1',
    price: 2132,
    volume: '500 мл',
    desc: 'Для натурального волосся',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-perm-lotion-2',
    category: 'special',
    brand: 'raywell',
    name: 'Лосьйон для завивки 2',
    price: 2132,
    volume: '500 мл',
    desc: 'Для фарбованого волосся',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-perm-lotion-3',
    category: 'special',
    brand: 'raywell',
    name: 'Лосьйон для завивки 3',
    price: 2132,
    volume: '500 мл',
    desc: 'Для пошкодженого волосся',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-perm-fixer',
    category: 'special',
    brand: 'raywell',
    name: 'Закріплювач для завивки',
    price: 1248,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-bioperm-0',
    category: 'special',
    brand: 'raywell',
    name: 'Біо завивка Perm 0',
    price: 936,
    volume: '250 мл',
    desc: 'Для жорсткого волосся',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-bioperm-1',
    category: 'special',
    brand: 'raywell',
    name: 'Біо завивка Perm 1',
    price: 936,
    volume: '250 мл',
    desc: 'Для натурального волосся',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-bioperm-2',
    category: 'special',
    brand: 'raywell',
    name: 'Біо завивка Perm 2',
    price: 936,
    volume: '250 мл',
    desc: 'Для фарбованого волосся',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-bioperm-fixer',
    category: 'special',
    brand: 'raywell',
    name: 'Закріплювач для біо завивки',
    price: 520,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-shampoo-loss-women-250',
    category: 'special',
    brand: 'raywell',
    name: 'Шампунь проти випадіння жіночий',
    price: 749,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: true,
  },
  {
    id: 'rw-shampoo-loss-women-1l',
    category: 'special',
    brand: 'raywell',
    name: 'Шампунь проти випадіння жіночий',
    price: 1456,
    volume: '1 л',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-shampoo-loss-men-250',
    category: 'special',
    brand: 'raywell',
    name: 'Шампунь проти випадіння чоловічий',
    price: 749,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-shampoo-loss-men-1l',
    category: 'special',
    brand: 'raywell',
    name: 'Шампунь проти випадіння чоловічий',
    price: 1394,
    volume: '1 л',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-ampules-loss-women',
    category: 'special',
    brand: 'raywell',
    name: 'Ампули проти випадіння для жінок',
    price: 1674,
    volume: '10 штук',
    desc: '',
    badge: null,
    popular: true,
  },
  {
    id: 'rw-ampules-loss-men',
    category: 'special',
    brand: 'raywell',
    name: 'Ампули проти випадіння для чоловіків',
    price: 1674,
    volume: '10 штук',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-lotion-loss',
    category: 'special',
    brand: 'raywell',
    name: 'Активуючий лосьйон проти випадіння',
    price: 1414,
    volume: '100 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-lotion-dandruff',
    category: 'special',
    brand: 'raywell',
    name: 'Лосьйон проти лупи',
    price: 1414,
    volume: '100 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-lotion-normalizing',
    category: 'special',
    brand: 'raywell',
    name: 'Лосьйон нормалізуючий',
    price: 1414,
    volume: '100 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-shampoo-dandruff-250',
    category: 'special',
    brand: 'raywell',
    name: 'Шампунь проти лупи',
    price: 790,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-shampoo-dandruff-1l',
    category: 'special',
    brand: 'raywell',
    name: 'Шампунь проти лупи',
    price: 1654,
    volume: '1 л',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-shampoo-normalizing-250',
    category: 'special',
    brand: 'raywell',
    name: 'Шампунь нормалізуючий',
    price: 749,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-shampoo-normalizing-1l',
    category: 'special',
    brand: 'raywell',
    name: 'Шампунь нормалізуючий',
    price: 1466,
    volume: '1 л',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'rw-scalp-scrub',
    category: 'special',
    brand: 'raywell',
    name: 'Скраб для шкіри голови',
    price: 988,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },

  // ══════════════════════════════════════════════════════
  //  INVIDIA — Стайлінг
  // ══════════════════════════════════════════════════════
  {
    id: 'inv-botoplus-cream',
    category: 'styling',
    brand: 'invidia',
    name: 'Незмивний розгладжуючий крем з колоїдним золотом Botoplus',
    price: 694,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'inv-botoplus-thermo',
    category: 'styling',
    brand: 'invidia',
    name: 'Крем термозахист 13 в 1 Botoplus',
    price: 836,
    volume: '200 мл',
    desc: 'Мультифункціональний термозахист',
    badge: 'hit',
    popular: true,
  },

  // ══════════════════════════════════════════════════════
  //  EXTREMO — Фарбування та освітлення
  // ══════════════════════════════════════════════════════
  {
    id: 'ex-haircolor-100',
    category: 'coloring',
    brand: 'extremo',
    name: 'Фарба Hair Color',
    price: 374,
    volume: '100 мл',
    desc: 'Стійка крем-фарба',
    badge: null,
    popular: true,
  },
  {
    id: 'ex-acidgloss-100',
    category: 'coloring',
    brand: 'extremo',
    name: 'Фарба Acid Gloss',
    price: 582,
    volume: '100 мл',
    desc: 'Безаміачна кислотна фарба',
    badge: 'new',
    popular: true,
  },
  {
    id: 'ex-oxid-1l',
    category: 'coloring',
    brand: 'extremo',
    name: 'Окисник',
    price: 458,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-oxid-200',
    category: 'coloring',
    brand: 'extremo',
    name: 'Окисник міні',
    price: 225,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-powder-blue',
    category: 'coloring',
    brand: 'extremo',
    name: 'Освітлююча пудра синя',
    price: 1747,
    volume: '500 г',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-powder-white',
    category: 'coloring',
    brand: 'extremo',
    name: 'Освітлююча пудра біла',
    price: 1331,
    volume: '500 г',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-powder-violet',
    category: 'coloring',
    brand: 'extremo',
    name: 'Освітлююча пудра фіолетова',
    price: 1747,
    volume: '500 г',
    desc: '',
    badge: null,
    popular: false,
  },

  // ══════════════════════════════════════════════════════
  //  EXTREMO — Догляд за волоссям
  // ══════════════════════════════════════════════════════
  {
    id: 'ex-tech-conditioner-5l',
    category: 'care',
    brand: 'extremo',
    name: 'Технічний кондиціонер',
    price: 2912,
    volume: '5 л',
    desc: 'Професійний об\'єм',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-botox-shampoo-argan',
    category: 'care',
    brand: 'extremo',
    name: 'Шампунь Ботокс гіалуронова кислота арган',
    price: 666,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-botox-cond-argan',
    category: 'care',
    brand: 'extremo',
    name: 'Кондиціонер Ботокс гіалуронова кислота арган',
    price: 666,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-botox-shampoo-keratin',
    category: 'care',
    brand: 'extremo',
    name: 'Шампунь Ботокс гіалуронова кислота кератин',
    price: 666,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-botox-cond-keratin',
    category: 'care',
    brand: 'extremo',
    name: 'Кондиціонер Ботокс гіалуронова кислота кератин',
    price: 666,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-botox-shampoo-karite',
    category: 'care',
    brand: 'extremo',
    name: 'Шампунь Ботокс гіалуронова кислота каріте',
    price: 666,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-botox-cond-karite',
    category: 'care',
    brand: 'extremo',
    name: 'Кондиціонер Ботокс гіалуронова кислота каріте',
    price: 666,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-total-shampoo',
    category: 'care',
    brand: 'extremo',
    name: 'Аміно-пептидний шампунь Total Protector',
    price: 772,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-total-mask',
    category: 'care',
    brand: 'extremo',
    name: 'Аміно-пептидна маска Total Protector',
    price: 1373,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-total-cream',
    category: 'care',
    brand: 'extremo',
    name: 'Аміно-пептидний крем Total Protector',
    price: 772,
    volume: '150 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-total-spray',
    category: 'care',
    brand: 'extremo',
    name: 'Аміно-пептидний спрей Total Protector',
    price: 789,
    volume: '150 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-nutra-shampoo',
    category: 'care',
    brand: 'extremo',
    name: 'Щоденний живильний шампунь Nutra Shine',
    price: 757,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-nutra-cond',
    category: 'care',
    brand: 'extremo',
    name: 'Ультраживильний кондиціонер Nutra Shine',
    price: 790,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-nutra-cream',
    category: 'care',
    brand: 'extremo',
    name: 'Ультраживильний крем Hydro-keratin Nutra Shine',
    price: 582,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-probiotic-shampoo',
    category: 'care',
    brand: 'extremo',
    name: 'Тривалентний шампунь з пробіотиком',
    price: 641,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-probiotic-cond',
    category: 'care',
    brand: 'extremo',
    name: 'Кондиціонер з пробіотиком',
    price: 641,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-probiotic-ampules',
    category: 'care',
    brand: 'extremo',
    name: 'Ампули інтенсив тривалент з пробіотиком',
    price: 1281,
    volume: '10x10 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-probiotic-exfoliant',
    category: 'care',
    brand: 'extremo',
    name: 'Детоксикуючий ексфоліант з пробіотиком',
    price: 441,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-crystals-argan',
    category: 'care',
    brand: 'extremo',
    name: 'Кристали з аргановою олією Silky&Soft',
    price: 899,
    volume: '100 мл',
    desc: '',
    badge: null,
    popular: true,
  },
  {
    id: 'ex-crystals-splitends',
    category: 'care',
    brand: 'extremo',
    name: 'Кристали інтенсив Split-Ends',
    price: 899,
    volume: '100 мл',
    desc: 'Для посічених кінчиків',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-crystals-macadamia',
    category: 'care',
    brand: 'extremo',
    name: 'Кристали Макадамія',
    price: 973,
    volume: '100 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-aftercolor-ampules',
    category: 'care',
    brand: 'extremo',
    name: 'Ампули After Color з муцином равлика',
    price: 1281,
    volume: '10x10 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-aftercolor-shampoo',
    category: 'care',
    brand: 'extremo',
    name: 'Шампунь After Color з муцином равлика',
    price: 666,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-aftercolor-mask-500',
    category: 'care',
    brand: 'extremo',
    name: 'Маска After Color з муцином равлика',
    price: 790,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-aftercolor-mask-250',
    category: 'care',
    brand: 'extremo',
    name: 'Маска After Color з муцином равлика',
    price: 557,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-aftercolor-fluid',
    category: 'care',
    brand: 'extremo',
    name: 'Флюїд After Color з муцином равлика',
    price: 832,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-curly-shampoo-karite',
    category: 'care',
    brand: 'extremo',
    name: 'Шампунь для кучерявого волосся з каріте',
    price: 557,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-curly-mask-karite-1l',
    category: 'care',
    brand: 'extremo',
    name: 'Маска для кучерявого волосся з каріте',
    price: 1290,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-curly-mask-karite-250',
    category: 'care',
    brand: 'extremo',
    name: 'Маска для кучерявого волосся з каріте',
    price: 557,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-antiyellow-shampoo',
    category: 'care',
    brand: 'extremo',
    name: 'Шампунь з ефектом анти-жовтизни',
    price: 666,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-thermo-10in1',
    category: 'care',
    brand: 'extremo',
    name: 'Крем термозахист 10 в 1',
    price: 749,
    volume: '250 мл',
    desc: 'Мультифункціональний термозахист',
    badge: 'hit',
    popular: true,
  },
  {
    id: 'ex-2phase-spray',
    category: 'care',
    brand: 'extremo',
    name: 'Двохфазний спрей реконструктор',
    price: 832,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },

  // ══════════════════════════════════════════════════════
  //  EXTREMO — Стайлінг
  // ══════════════════════════════════════════════════════
  {
    id: 'ex-wax-strong',
    category: 'styling',
    brand: 'extremo',
    name: 'Вакса сильної фіксації',
    price: 582,
    volume: '100 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-wax-matte',
    category: 'styling',
    brand: 'extremo',
    name: 'Вакса з матовим ефектом',
    price: 582,
    volume: '100 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-volume-powder',
    category: 'styling',
    brand: 'extremo',
    name: 'Пудра для об\'єму',
    price: 1082,
    volume: '20 г',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-curly-cream',
    category: 'styling',
    brand: 'extremo',
    name: 'Крем для кучерявого волосся',
    price: 582,
    volume: '175 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-texture-spray',
    category: 'styling',
    brand: 'extremo',
    name: 'Текстурний спрей для об\'єму',
    price: 532,
    volume: '150 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-gel-spray',
    category: 'styling',
    brand: 'extremo',
    name: 'Фіксуючий гель-спрей сильної фіксації',
    price: 532,
    volume: '150 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-gel-strong',
    category: 'styling',
    brand: 'extremo',
    name: 'Гель сильної фіксації',
    price: 449,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },

  // ══════════════════════════════════════════════════════
  //  EXTREMO — Спеціальний догляд
  // ══════════════════════════════════════════════════════
  {
    id: 'ex-total-skin-cream',
    category: 'special',
    brand: 'extremo',
    name: 'Захисний крем для хімічних сумішей Total Protector',
    price: 582,
    volume: '200 мл',
    desc: 'Захист шкіри при фарбуванні',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-perm-012',
    category: 'special',
    brand: 'extremo',
    name: 'Завивка (0/1/2)',
    price: 1165,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'ex-perm-fixer',
    category: 'special',
    brand: 'extremo',
    name: 'Закріплювач для завивки',
    price: 399,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },

  // ══════════════════════════════════════════════════════
  //  ENVIE — Фарбування та освітлення
  // ══════════════════════════════════════════════════════
  {
    id: 'env-viacolor-remover',
    category: 'coloring',
    brand: 'envie',
    name: 'Рідина для видалення фарби Viacolor',
    price: 853,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-bleach-oil',
    category: 'coloring',
    brand: 'envie',
    name: 'Освітлююча олія',
    price: 1882,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-color-masks',
    category: 'coloring',
    brand: 'envie',
    name: 'Кольорові маски (6 кольорів)',
    price: 1123,
    volume: '150 мл',
    desc: 'Тонуючі маски прямої дії',
    badge: 'new',
    popular: true,
  },

  // ══════════════════════════════════════════════════════
  //  ENVIE — Догляд за волоссям
  // ══════════════════════════════════════════════════════
  {
    id: 'env-preshampoo',
    category: 'care',
    brand: 'envie',
    name: 'Pre-Shampoo глибокої очистки',
    price: 1278,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-daily-shampoo-1l',
    category: 'care',
    brand: 'envie',
    name: 'Щоденний шампунь Daily Shine',
    price: 1196,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-daily-mask-1l',
    category: 'care',
    brand: 'envie',
    name: 'Щоденна маска Daily Shine',
    price: 1196,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-daily-cond-500',
    category: 'care',
    brand: 'envie',
    name: 'Щоденний кондиціонер Daily Shine',
    price: 936,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-daily-shampoo-250',
    category: 'care',
    brand: 'envie',
    name: 'Щоденний шампунь Daily Shine',
    price: 624,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-daily-filler',
    category: 'care',
    brand: 'envie',
    name: 'Крем-філлер Daily Shine',
    price: 863,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-no-orange-mask-1l',
    category: 'care',
    brand: 'envie',
    name: 'Маска No Orange',
    price: 1331,
    volume: '1 л',
    desc: 'Нейтралізація помаранчевих відтінків',
    badge: null,
    popular: false,
  },
  {
    id: 'env-no-orange-mask-250',
    category: 'care',
    brand: 'envie',
    name: 'Маска No Orange',
    price: 603,
    volume: '250 мл',
    desc: 'Нейтралізація помаранчевих відтінків',
    badge: null,
    popular: false,
  },
  {
    id: 'env-keratin-shampoo-1l',
    category: 'care',
    brand: 'envie',
    name: 'Шампунь Sublime Keratin',
    price: 1248,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-keratin-shampoo-250',
    category: 'care',
    brand: 'envie',
    name: 'Шампунь Sublime Keratin',
    price: 624,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-keratin-mask-1l',
    category: 'care',
    brand: 'envie',
    name: 'Маска Sublime Keratin',
    price: 1248,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-keratin-mask-250',
    category: 'care',
    brand: 'envie',
    name: 'Маска Sublime Keratin',
    price: 624,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-keratin-ampules',
    category: 'care',
    brand: 'envie',
    name: 'Ампули реконструкції Keratin',
    price: 1716,
    volume: '10х10 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-keratin-thermo-spray',
    category: 'care',
    brand: 'envie',
    name: 'Термоактивний спрей Sublime',
    price: 863,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-milk-shampoo-1l',
    category: 'care',
    brand: 'envie',
    name: 'Шампунь Milk з молочними протеїнами',
    price: 1206,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-milk-shampoo-250',
    category: 'care',
    brand: 'envie',
    name: 'Шампунь Milk з молочними протеїнами',
    price: 624,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-milk-mask-1l',
    category: 'care',
    brand: 'envie',
    name: 'Маска Milk з молочними протеїнами',
    price: 1518,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-milk-mask-250',
    category: 'care',
    brand: 'envie',
    name: 'Маска Milk з молочними протеїнами',
    price: 624,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-milk-thermo-10in1',
    category: 'care',
    brand: 'envie',
    name: 'Крем термозахист 10 в 1 Milk',
    price: 1019,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-milk-2phase',
    category: 'care',
    brand: 'envie',
    name: 'Двохфазний спрей Milk',
    price: 988,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-milk-fluid',
    category: 'care',
    brand: 'envie',
    name: 'Флюїд розгладжуючий Milk',
    price: 936,
    volume: '150 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-milk-oligo',
    category: 'care',
    brand: 'envie',
    name: 'Система оліго-мінералізації Milk',
    price: 1716,
    volume: '10х10 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-milk-crystals',
    category: 'care',
    brand: 'envie',
    name: 'Кристали Milk з аргановою олією',
    price: 1186,
    volume: '100 мл',
    desc: '',
    badge: 'hit',
    popular: true,
  },
  {
    id: 'env-milk-mousse',
    category: 'care',
    brand: 'envie',
    name: 'Молочний мус-крем Milk',
    price: 1040,
    volume: '300 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-cromactive-shampoo-1l',
    category: 'care',
    brand: 'envie',
    name: 'Шампунь Cromactive захист кольору',
    price: 1227,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-cromactive-shampoo-250',
    category: 'care',
    brand: 'envie',
    name: 'Шампунь Cromactive захист кольору',
    price: 624,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-cromactive-mask-1l',
    category: 'care',
    brand: 'envie',
    name: 'Маска Cromactive захист кольору',
    price: 1248,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-cromactive-mask-250',
    category: 'care',
    brand: 'envie',
    name: 'Маска Cromactive захист кольору',
    price: 624,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-cromactive-spray',
    category: 'care',
    brand: 'envie',
    name: 'Спрей Cromactive з екстрактом граната',
    price: 676,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-cromactive-crystals',
    category: 'care',
    brand: 'envie',
    name: 'Кристали Cromactive для захисту кольору',
    price: 1009,
    volume: '100 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-murumuru-shampoo',
    category: 'care',
    brand: 'envie',
    name: 'Шампунь для фарбованого з олією муру муру',
    price: 998,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-murumuru-cond',
    category: 'care',
    brand: 'envie',
    name: 'Кондиціонер для фарбованого з олією муру муру',
    price: 884,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-vitaminA-mask',
    category: 'care',
    brand: 'envie',
    name: 'Маска для фарбованого з вітаміном А',
    price: 988,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-moist-shampoo',
    category: 'care',
    brand: 'envie',
    name: 'Шампунь зволожуючий для сухого і кучерявого волосся',
    price: 998,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-moist-cond',
    category: 'care',
    brand: 'envie',
    name: 'Кондиціонер зволожуючий з екстрактом льону',
    price: 936,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-moist-mask',
    category: 'care',
    brand: 'envie',
    name: 'Маска зволожуюча для сухого і кучерявого',
    price: 1040,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-volume-shampoo',
    category: 'care',
    brand: 'envie',
    name: 'Шампунь для об\'єму тонкого і ламкого волосся',
    price: 998,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-volume-lotion-spray',
    category: 'care',
    brand: 'envie',
    name: 'Лосьйон-спрей для об\'єму та реконструкції',
    price: 884,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-smooth-shampoo',
    category: 'care',
    brand: 'envie',
    name: 'Шампунь розгладжуючий',
    price: 998,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-smooth-cond',
    category: 'care',
    brand: 'envie',
    name: 'Кондиціонер розгладжуючий',
    price: 1040,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-2in1-shampoo-gel',
    category: 'care',
    brand: 'envie',
    name: 'Шампунь+гель 2в1 для щоденного використання',
    price: 936,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },

  // ══════════════════════════════════════════════════════
  //  ENVIE — Відновлення
  // ══════════════════════════════════════════════════════
  {
    id: 'env-sos-shampoo-1l',
    category: 'repair',
    brand: 'envie',
    name: 'Шампунь SOS Express з амінокислотами',
    price: 1612,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-sos-shampoo-250',
    category: 'repair',
    brand: 'envie',
    name: 'Шампунь SOS Express з амінокислотами',
    price: 697,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-sos-mask-1l',
    category: 'repair',
    brand: 'envie',
    name: 'Маска SOS Express з амінокислотами',
    price: 1747,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-sos-mask-250',
    category: 'repair',
    brand: 'envie',
    name: 'Маска SOS Express з амінокислотами',
    price: 780,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-sos-cream',
    category: 'repair',
    brand: 'envie',
    name: 'Оксамитовий незмивний крем SOS Express',
    price: 676,
    volume: '100 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-sos-lamellar',
    category: 'repair',
    brand: 'envie',
    name: 'Ламелярна вода для відновлення SOS Express',
    price: 1050,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-molecular-shampoo',
    category: 'repair',
    brand: 'envie',
    name: 'Шампунь Molecular Bond Repair',
    price: 839,
    volume: '250 мл',
    desc: 'Молекулярне відновлення',
    badge: 'new',
    popular: true,
  },
  {
    id: 'env-molecular-mask',
    category: 'repair',
    brand: 'envie',
    name: 'Маска Molecular Bond Repair',
    price: 1241,
    volume: '250 мл',
    desc: 'Молекулярне відновлення',
    badge: 'new',
    popular: true,
  },
  {
    id: 'env-molecular-spray',
    category: 'repair',
    brand: 'envie',
    name: 'Молекулярний термозахисний спрей',
    price: 1022,
    volume: '100 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-nutraplex',
    category: 'repair',
    brand: 'envie',
    name: 'Додаток Nutra-Plex Molecular Bond Repair',
    price: 913,
    volume: '250 мл',
    desc: 'Захист при хімічних процедурах',
    badge: null,
    popular: false,
  },

  // ══════════════════════════════════════════════════════
  //  ENVIE — Стайлінг
  // ══════════════════════════════════════════════════════
  {
    id: 'env-smoothing-cream',
    category: 'styling',
    brand: 'envie',
    name: 'Випрямляючий розчин Smoothing Cream',
    price: 2920,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-rebonder',
    category: 'styling',
    brand: 'envie',
    name: 'Фікс відновлюючий розчин Re-Bonder',
    price: 1825,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-sea-spray',
    category: 'styling',
    brand: 'envie',
    name: 'Спрей морська вода',
    price: 884,
    volume: '200 мл',
    desc: 'Текстурний спрей з морською сіллю',
    badge: null,
    popular: false,
  },
  {
    id: 'env-thermo-vegan',
    category: 'styling',
    brand: 'envie',
    name: 'Спрей-термозахист Vegan',
    price: 842,
    volume: '200 мл',
    desc: '',
    badge: null,
    popular: false,
  },

  // ══════════════════════════════════════════════════════
  //  ENVIE — Спеціальний догляд
  // ══════════════════════════════════════════════════════
  {
    id: 'env-grow-shampoo',
    category: 'special',
    brand: 'envie',
    name: 'Шампунь Energizing Grow',
    price: 707,
    volume: '250 мл',
    desc: 'Стимулюючий шампунь для росту',
    badge: null,
    popular: false,
  },
  {
    id: 'env-dandruff-shampoo-1l',
    category: 'special',
    brand: 'envie',
    name: 'Шампунь проти лупи',
    price: 1196,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-dandruff-shampoo-250',
    category: 'special',
    brand: 'envie',
    name: 'Шампунь проти лупи',
    price: 624,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-sebo-shampoo-250',
    category: 'special',
    brand: 'envie',
    name: 'Шампунь себорегулюючий',
    price: 624,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-sebo-shampoo-1l',
    category: 'special',
    brand: 'envie',
    name: 'Шампунь себорегулюючий',
    price: 1279,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-growth-shampoo-250',
    category: 'special',
    brand: 'envie',
    name: 'Шампунь для росту волосся',
    price: 707,
    volume: '250 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-growth-shampoo-1l',
    category: 'special',
    brand: 'envie',
    name: 'Шампунь для росту волосся Revitalize',
    price: 1352,
    volume: '1000 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-growth-ampules',
    category: 'special',
    brand: 'envie',
    name: 'Ампули для росту волосся Revitalize',
    price: 1820,
    volume: '10x10 мл',
    desc: '',
    badge: 'hit',
    popular: true,
  },
  {
    id: 'env-growth-lotion',
    category: 'special',
    brand: 'envie',
    name: 'Щоденний лосьйон Revitalize',
    price: 1581,
    volume: '100 мл',
    desc: 'Лосьйон для стимуляції росту',
    badge: null,
    popular: false,
  },
  {
    id: 'env-dandruff-shampoo-500',
    category: 'special',
    brand: 'envie',
    name: 'Шампунь лікувальний проти лупи',
    price: 1019,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-normalizing-shampoo',
    category: 'special',
    brand: 'envie',
    name: 'Шампунь нормалізуючий для жирної шкіри',
    price: 998,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-loss-women-shampoo',
    category: 'special',
    brand: 'envie',
    name: 'Шампунь лікувальний проти випадіння (жінки)',
    price: 1040,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-loss-women-lotion',
    category: 'special',
    brand: 'envie',
    name: 'Лосьйон активуючий для кореня (жінки)',
    price: 1508,
    volume: '8x10 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-loss-men-shampoo',
    category: 'special',
    brand: 'envie',
    name: 'Шампунь лікувальний проти випадіння (чоловіки)',
    price: 1040,
    volume: '500 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-loss-men-lotion',
    category: 'special',
    brand: 'envie',
    name: 'Лосьйон активуючий для кореня (чоловіки)',
    price: 1560,
    volume: '8x10 мл',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-bag-viola',
    category: 'special',
    brand: 'envie',
    name: 'Косметичка Viola',
    price: 654,
    volume: '24x24x15',
    desc: '',
    badge: null,
    popular: false,
  },
  {
    id: 'env-bag-blue',
    category: 'special',
    brand: 'envie',
    name: 'Косметичка Blue',
    price: 823,
    volume: '13x20x10',
    desc: '',
    badge: null,
    popular: false,
  },
];
