/* ═══════════════════════════════════════════════════════
   SVS Beauty Space — Shop Product Data
   Edit this file to add/remove/update products
   ═══════════════════════════════════════════════════════ */

var SHOP_CATEGORIES = [
  { id: 'hair-care',   name: 'Догляд за волоссям',  icon: '✦' },
  { id: 'coloring',    name: 'Фарбування',          icon: '◆' },
  { id: 'styling',     name: 'Стайлінг',            icon: '◇' },
  { id: 'nails',       name: 'Нігті',               icon: '◈' },
  { id: 'tools',       name: 'Інструменти',         icon: '⬥' },
];

var SHOP_PRODUCTS = [
  // ── Hair Care ──
  {
    id: 'shampoo-repair',
    category: 'hair-care',
    name: 'Відновлювальний шампунь',
    brand: 'Professional',
    price: 580,
    oldPrice: null,
    volume: '300 мл',
    desc: 'Глибоке очищення та відновлення пошкодженого волосся. Кератиновий комплекс.',
    img: 'img/shop/shampoo-repair.jpg',
    badge: null,
    popular: true,
  },
  {
    id: 'mask-keratin',
    category: 'hair-care',
    name: 'Кератинова маска',
    brand: 'Professional',
    price: 720,
    oldPrice: 850,
    volume: '250 мл',
    desc: 'Інтенсивне відновлення структури. Результат після першого застосування.',
    img: 'img/shop/mask-keratin.jpg',
    badge: 'sale',
    popular: true,
  },
  {
    id: 'oil-argan',
    category: 'hair-care',
    name: 'Арганова олія для волосся',
    brand: 'Professional',
    price: 490,
    oldPrice: null,
    volume: '100 мл',
    desc: 'Живлення, блиск, захист від термообробки. Не обтяжує.',
    img: 'img/shop/oil-argan.jpg',
    badge: 'hit',
    popular: true,
  },
  {
    id: 'serum-ends',
    category: 'hair-care',
    name: 'Сироватка для кінчиків',
    brand: 'Professional',
    price: 420,
    oldPrice: null,
    volume: '50 мл',
    desc: 'Запечатує посічені кінчики, надає гладкість та сяйво.',
    img: 'img/shop/serum-ends.jpg',
    badge: null,
    popular: false,
  },

  // ── Coloring ──
  {
    id: 'color-cream',
    category: 'coloring',
    name: 'Крем-фарба стійка',
    brand: 'Professional',
    price: 350,
    oldPrice: null,
    volume: '100 мл',
    desc: '100% покриття сивини. Щадна формула з маслом макадамії.',
    img: 'img/shop/color-cream.jpg',
    badge: null,
    popular: true,
  },
  {
    id: 'oxidant-6',
    category: 'coloring',
    name: 'Оксидант 6%',
    brand: 'Professional',
    price: 280,
    oldPrice: null,
    volume: '1000 мл',
    desc: 'Стабільна формула для рівномірного освітлення.',
    img: 'img/shop/oxidant.jpg',
    badge: null,
    popular: false,
  },
  {
    id: 'bleach-powder',
    category: 'coloring',
    name: 'Освітлювальна пудра',
    brand: 'Professional',
    price: 650,
    oldPrice: null,
    volume: '500 г',
    desc: 'До 9 тонів освітлення. Антижовтий ефект.',
    img: 'img/shop/bleach-powder.jpg',
    badge: null,
    popular: false,
  },

  // ── Styling ──
  {
    id: 'spray-thermal',
    category: 'styling',
    name: 'Термозахисний спрей',
    brand: 'Professional',
    price: 440,
    oldPrice: null,
    volume: '200 мл',
    desc: 'Захист до 230°C. Легка фіксація без склеювання.',
    img: 'img/shop/spray-thermal.jpg',
    badge: 'hit',
    popular: true,
  },
  {
    id: 'hairspray-strong',
    category: 'styling',
    name: 'Лак сильної фіксації',
    brand: 'Professional',
    price: 380,
    oldPrice: null,
    volume: '400 мл',
    desc: 'Тривала фіксація без обтяження. Легко вичісується.',
    img: 'img/shop/hairspray.jpg',
    badge: null,
    popular: false,
  },

  // ── Nails ──
  {
    id: 'gel-base',
    category: 'nails',
    name: 'База для гель-лаку',
    brand: 'Professional',
    price: 320,
    oldPrice: null,
    volume: '12 мл',
    desc: 'Самовирівнювальна формула. Ідеальна адгезія.',
    img: 'img/shop/gel-base.jpg',
    badge: null,
    popular: true,
  },
  {
    id: 'gel-top',
    category: 'nails',
    name: 'Топ без липкого шару',
    brand: 'Professional',
    price: 340,
    oldPrice: null,
    volume: '12 мл',
    desc: 'Дзеркальний блиск. Захист від сколів до 3 тижнів.',
    img: 'img/shop/gel-top.jpg',
    badge: null,
    popular: false,
  },
  {
    id: 'cuticle-oil',
    category: 'nails',
    name: 'Олія для кутикули',
    brand: 'Professional',
    price: 190,
    oldPrice: 250,
    volume: '15 мл',
    desc: 'Живлення та зволоження. Аромат жасмину.',
    img: 'img/shop/cuticle-oil.jpg',
    badge: 'sale',
    popular: true,
  },

  // ── Tools ──
  {
    id: 'brush-round',
    category: 'tools',
    name: 'Брашинг керамічний',
    brand: 'Professional',
    price: 520,
    oldPrice: null,
    volume: 'Ø 45 мм',
    desc: 'Антистатичне покриття. Турмалінова кераміка.',
    img: 'img/shop/brush-round.jpg',
    badge: null,
    popular: false,
  },
  {
    id: 'clips-set',
    category: 'tools',
    name: 'Затискачі для волосся',
    brand: 'Professional',
    price: 180,
    oldPrice: null,
    volume: '6 шт',
    desc: 'Карбонове покриття. Не пошкоджують волосся.',
    img: 'img/shop/clips.jpg',
    badge: null,
    popular: false,
  },
];
